### ISSUE TITLE
Frequence/FREQ should be given in definitions

### ISSUE THREAD

**Issue by Haoran877** [kherz/pulseq-cest-library#30]
For some evaluations we need frequency of the SEQ,file. E.g. for CEST or WASSABI fitting.
Thus, it should be added to all SEQ.file definition block.

**Comment by mzaiss** [comment]
also: wouldnt it be better to move to FREQ completely, as pulseq is in Hz throughout?
so I would vote for 
def.FREQ           = 123.43               ; % B0*gamma*ppm [Hz]

and to put this in the very beginning of each file, because if something has to be changed for a local scanner, it is most probably the exact FREQ of the scanner.

**Comment by mzaiss** [comment]
def.FREQ = 123.43 ; % ~B0 gamma ppm [Hz]

**Comment by mzaiss** [comment]
put this part into a write_defs function (in pulseq-CEST)

def_fields = fieldnames(seq_defs);
for n_id = 1:numel(def_fields)
    seq.setDefinition(def_fields{n_id}, seq_defs.(def_fields{n_id}));
end

here errors can be fetched.
